name: Feature Request
description: Suggest an idea for Future Energy Outlook Python Client
title: "ENH: "
labels: [Enhancement, Needs Triage]

body:
  - type: checkboxes
    id: checks
    attributes:
      label: Feature Type
      description: Please check what type of feature request you would like to propose.
      options:
        - label: >
            Adding new functionality to Future Energy Outlook Python Client
        - label: >
            Changing existing functionality in Future Energy Outlook Python Client
        - label: >
            Removing existing functionality in Future Energy Outlook Python Client
  - type: textarea
    id: description
    attributes:
      label: Problem Description
      description: >
        Please describe what problem the feature would solve, e.g. "I wish I could use Future Energy Outlook Python Client to ..."
      placeholder: >
        I wish I could use Future Energy Outlook Python Client to..
    validations:
      required: true
  - type: textarea
    id: feature
    attributes:
      label: Feature Description
      description: >
        Please describe how the new feature would be implemented, using pseudocode if relevant.
      placeholder: >
    validations:
      required: true
